---
# Minor FreeBSD hardening
- hosts: freebsd
  vars_files:
    - vars.yml
  tasks:
    - name: Minimal FreeBSD hardening
      block:
      - name: Harden sysctl settings
        sysctl:
          name: "{{ item.key }}"
          value: "{{ item.value }}"
          state: present
        with_dict:
          kern.coredump: 0
          kern.securelevel: 1
          security.bsd.see_other_uids: 0
          security.bsd.see_other_gids: 0
          security.bsd.unprivileged_read_msgbuf: 0
      - name: Enable firewall
        blockinfile:
          path: /etc/rc.conf
          block: |
            firewall_enable="YES"
            firewall_type="open"
      # https://www.freebsd.org/doc/handbook/audit-config.html
      - name: Enable & start auditing
        service:
          name: auditd
          enabled: yes
          state: started
      - name: Create audit log rotation
        cron:
          name: "audit log rotation"
          hour: "*/12"
          minute: "0"
          job: /usr/sbin/audit -n 1>/dev/null
      # https://www.freebsd.org/doc/handbook/consoles.html#consoles-singleuser
      - name: Ask for password in single User Mode
        replace:
          path: /etc/ttys
          regexp: '^(console\s+.+\s+)secure$'
          replace: '\g<1>insecure'
          validate: '/usr/bin/grep "^console.\+insecure$" %s'
      - name: Set uucp user's shell to nologin
        user:
          name: uucp
          shell: /sbin/nologin
      - name: Remove the user 'toor'
        user:
          name: toor
          state: absent
          remove: yes
      # https://www.freebsd.org/doc/handbook/security-pkg.html
      - name: Stat /etc/periodic.conf
        stat:
          path: /etc/periodic.conf
        register: stat_result
      - name: Run pkg audit daily
        replace:
          path: /etc/periodic.conf
          regexp: '^(daily_status_security_pkgaudit_enable)="[A-Z]+"$'
          replace: '\g<1>="YES"'
          validate: '/usr/bin/grep "^daily_status_security_pkgaudit_enable=\"YES\"$" %s'
      # https://www.freebsd.org/doc/handbook/security-accounting.html#idp56794616
      - name: Enable process accounting
        block:
        - name: Create process accounting file
          copy:
            content: ""
            dest: /var/account/acct
            force: no
            group: wheel
            owner: root
            mode: 0600
        - name: Start process accounting
          command: accton /var/account/acct
        - name: Enable accounting
          service:
            name: accounting
            enabled: yes
      - name: Get kern.ident sysctl value
        command: sysctl -n kern.ident
        register: kern_ident
      - name: Add rrdcached to allowed_services
        set_fact:
          allowed_services: "{{ allowed_services + [ \"rrdcached\" ] }}"
        when: kern_ident.stdout == "FREENAS64"
      - name: 'TCP wrappers: create /etc/hosts.allow'
        template:
          src: "{{ playbook_dir }}/templates/hosts.allow-{{ ansible_system }}.j2"
          dest: /etc/hosts.allow
      - name: chmod /root
        file:
          path: /root
          mode: '0700'
      - name: Set default umask to 077
        replace:
          path: /etc/login.conf
          regexp: '^(\s+:umask=)022:\\$'
          replace: '\g<1>077:\\'
      - name: Update the login.conf database
        command: cap_mkdb
      become: yes
      when: ansible_distribution == "FreeBSD"
