---
- name: rkhunter
  block:
  - name: Install rkhunter (Debian)
    apt:
      name: rkhunter
      update_cache: yes
    when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
    tags: packages
  - name: 'Create /etc/rkhunter.conf'
    template:
      src: "{{ playbook_dir }}/templates/rkhunter.conf.j2"
      dest: /etc/rkhunter.conf
      mode: '0400'
      owner: root
      group: root
  # https://sourceforge.net/p/rkhunter/rkh_code/ci/master/tree/files/FAQ: "3.3) How can I automatically run Rootkit Hunter every day?"
  # We don't use --update as rkhunter.sourceforge.net doesn't have HTTPS
  - name: Add rkhunter cronjob
    cron:
      name: "Run rkhunter"
      minute: "30"
      hour: "5"
      job: "/usr/bin/test -x /usr/bin/rkhunter && /usr/bin/rkhunter --cronjob --rwo"
    when: ansible_distribution != "Debian"
  - name: Enable daily rkhunter check in Debian
    replace:
      path: /etc/default/rkhunter
      regexp: '^(CRON_DAILY_RUN=).*'
      replace: '\g<1>"yes"'
    when: ansible_distribution == "Debian"
  - name: Create rkhunter.dat
    command: /usr/bin/rkhunter --propupd
    args:
      creates: /var/lib/rkhunter/db/rkhunter.dat
  become: yes
