---
- name: Install glibc package (Slackware)
  when: ansible_distribution == "Slackware"
  become: yes
  command: slackpkg -batch=on -default_answer=y install glibc
  tags:
  - packages
- name: 'Check that some user(s) exist in "sudo" group'
  getent:
    database: group
    key: sudo
  failed_when: getent_group.sudo[2] == ""
  when: ansible_distribution == "Debian"
- name: 'Check that some user(s) exist in "wheel" group'
  getent:
    database: group
    key: wheel
  failed_when: getent_group.wheel[2] == "" or getent_group.wheel[2] == "root"
  when: ansible_distribution == "Slackware"
- name: 'Configure /etc/sudoers'
  block:
  - name: 'Create /etc/sudoers.new'
    template:
      src: "{{ playbook_dir }}/templates/sudoers.j2"
      dest: /etc/sudoers.new
      mode: '0440'
      owner: root
      group: root
  - name: Create /etc/sudo_env
    copy:
      content: "LESSSECURE=1\nPAGER=/usr/bin/less\nMANPAGER=/usr/bin/less\nSYSTEMD_PAGER=/usr/bin/less\nTMOUT=900\n"
      dest: /etc/sudo_env
      owner: root
      group: root
      mode: '0400'
      force: no
  # https://jpmens.net/2013/02/06/don-t-try-this-at-the-office-etc-sudoers/
  - name: 'Validate /etc/sudoers.new'
    command: visudo -cs -f /etc/sudoers.new
  - name: 'Copy /etc/sudoers.new to /etc/sudoers'
    copy:
      remote_src: yes
      src: /etc/sudoers.new
      dest: /etc/sudoers
  - name: 'Remove /etc/sudoers.new'
    file:
      path: /etc/sudoers.new
      state: absent
  when: ansible_distribution == "Slackware" or ansible_distribution == "Debian"
  become: yes
# https://www.raspberrypi.org/documentation/configuration/security.md
- name: 'Remove /etc/sudoers.d/010_pi-nopasswd'
  become: yes
  file:
    path: /etc/sudoers.d/010_pi-nopasswd
    state: absent
  when: ansible_distribution == "Debian" and ansible_lsb.id == "Raspbian"
- include: filesystem-sudoers.yml
